# Just for Mysterium (We need to downgrade them [i.e. replace with low-poly facsimiles] afterwards)
MysteriumShowOff: &MysteriumShowOff
   - G_BubbleGarden
   - G_Terrain
   - G_SpikeGarden

## A: All-Encompassing
AGeneral: &AGeneral
   - A_Journals
   - *MysteriumShowOff

## S: Shared
SRivenBase: &SRivenBase
   - S_Lighting_Riven
   - S_PostProcessing_Riven
   - S_Ocean_Riven

## B: Boiler Island
BBase: &BBase
   - *AGeneral
   - *SRivenBase
   - B_Terrain # TODO separate into parts
BEastSide:
   - *BBase
   - S_GreatBridge
   - B_UpperWalkwayTunnel
   - T_SuperDome
   - T_Terrain
   - B_Stuff

## G: Garden Island
# Bases
GBase: &GBase
   - *AGeneral
   - *SRivenBase
GUpsideBase: &GUpsideBase
   - G_Terrain
   - G_WahrkTankUpper
   - G_BubbleGarden
   - G_Connector
# Specifics
GUpsideExterior:
   - *GBase
   - *GUpsideBase
   - G_SpikeGarden
GUpsideInterior:
   - *GBase
   - *GUpsideBase
   - G_MaglevDock_B
GDownside:
   - *GBase
   - G_MaglevDock_J
   - G_WahrkTankLower

## T: Temple Island
# Bases
TBase: &TBase
   - *AGeneral
   - *SRivenBase
   - T_Terrain
TCommonOutside: &TCommonOutside
   # These should be removed or at least downgraded after Mysterium:
   - B_UpperWalkwayTunnel
   - B_Terrain
TWestSide:
   - *TBase
   - *TCommonOutside
   - S_GreatBridge
   - T_SuperDome
   - T_GateRoom
TNorthSide:
   - *TBase
   - *TCommonOutside
   - S_GreatBridge
   - T_GateRoom
   - T_SuperDome
TFissureDistrict:
   - *TBase
   - T_GateRoom
   - T_Plateaus
   - T_NewTemple
   - T_SuperDome
TSpiderTunnelDistrict:
   - *TBase
   - T_GateRoom # :( wish we didn't need this
   - T_Plateaus
   - T_SpiderChairRoomInterior
   - T_NewTemple
   - S_Maglev_TJ
   - T_SuperDome # TODO can downgrade this, so it's just the superdome exterior
TMaglevDistrict:
   - *TBase
   - *TCommonOutside
   - S_Maglev_TJ